# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=0, unique=True, verbose_name='\u672c\u7ea7\u4ee3\u7801')),
                ('pid', models.IntegerField(default=0, verbose_name='\u7236\u7ea7\u4ee3\u7801')),
                ('full_name', models.CharField(default='', max_length=50, verbose_name='\u672c\u7ea7\u5168\u79f0')),
                ('level', models.IntegerField(default=0, verbose_name='\u672c\u7ea7\u7ea7\u522b')),
            ],
            options={
                'db_table': 'data_city_codes',
                'verbose_name': '\u57ce\u5e02\u6570\u636e',
                'verbose_name_plural': '\u57ce\u5e02\u6570\u636e',
            },
        ),
    ]
