# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import spider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='', help_text='\u683c\u5f0f\u4e3anews_search_163', max_length=100, unique=True, verbose_name='\u914d\u7f6e\u540d\u79f0')),
                ('site_name', models.CharField(default='', help_text='\u8bf7\u586b\u5199\u51c6\u786e\u4ee5\u65b9\u4fbf\u67e5\u8be2', max_length=100, verbose_name='\u7f51\u7ad9\u540d\u79f0')),
                ('site_domain', models.URLField(default='', help_text='\u683c\u5f0f\u4e3amusic.163.com', max_length=100, verbose_name='\u7f51\u7ad9\u57df\u540d')),
                ('config_text', models.TextField(default='', help_text='Json\u683c\u5f0f\u6587\u4ef6\u952e\u548c\u503c\u8bf7\u7528 " \u53cc\u5f15\u53f7', validators=[spider.models.validate_json], verbose_name='\u914d\u7f6e\u5185\u5bb9')),
                ('config_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'spider_configs',
                'verbose_name': '\u914d\u7f6e\u6587\u4ef6',
                'verbose_name_plural': '\u914d\u7f6e\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100, unique=True, verbose_name='\u7f51\u7edc\u534f\u8bae')),
                ('ifadd', models.IntegerField(default=0, editable=False, verbose_name='\u662f\u5426\u6dfb\u52a0')),
            ],
            options={
                'db_table': 'spider_keyword',
                'verbose_name': '\u5173\u952e\u8bcd\u8bed',
                'verbose_name_plural': '\u5173\u952e\u8bcd\u8bed',
            },
        ),
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='', editable=False, max_length=200, unique=True, verbose_name='\u5de5\u4f5c\u5e8f\u53f7')),
                ('bot_ip', models.GenericIPAddressField(default='0.0.0.0', editable=False, verbose_name='\u673a\u5668\u5730\u5740')),
                ('bot_name', models.CharField(default='', editable=False, max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('spider_name', models.CharField(default='', editable=False, max_length=100, verbose_name='\u722c\u866b\u540d\u79f0')),
                ('config_path', models.CharField(default='', editable=False, max_length=100, verbose_name='\u914d\u7f6e\u540d\u79f0')),
                ('finish_reason', models.CharField(default='', editable=False, max_length=100, verbose_name='\u5b8c\u6210\u539f\u56e0')),
                ('dropped_count', models.IntegerField(default=0, editable=False, verbose_name='\u4e22\u6389\u6570\u76ee')),
                ('scraped_count', models.IntegerField(default=0, editable=False, verbose_name='\u91c7\u96c6\u6570\u76ee')),
                ('start_time', models.DateTimeField(editable=False, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(editable=False, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('elapsed_time', models.IntegerField(default=0, editable=False, verbose_name='\u8fd0\u884c\u65f6\u957f')),
            ],
            options={
                'db_table': 'spider_monitors',
                'verbose_name': '\u76d1\u6d4b\u7ba1\u7406',
                'verbose_name_plural': '\u76d1\u6d4b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default='http', editable=False, max_length=50, verbose_name='\u7f51\u7edc\u534f\u8bae')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', editable=False, verbose_name='\u7f51\u7edc\u5730\u5740')),
                ('port', models.IntegerField(default=80, editable=False, verbose_name='\u7f51\u7edc\u7aef\u53e3')),
                ('website', models.CharField(default='', editable=False, max_length=50, verbose_name='\u6293\u53d6\u7f51\u7ad9')),
                ('ifadd', models.IntegerField(default=0, editable=False, verbose_name='\u662f\u5426\u6dfb\u52a0')),
            ],
            options={
                'db_table': 'spider_proxy',
                'verbose_name': '\u4ee3\u7406\u5730\u5740',
                'verbose_name_plural': '\u4ee3\u7406\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='', help_text='\u8bf7\u586b\u5199\u914d\u7f6e\u6587\u4ef6\u91cc\u5df2\u6709\u7684\u6587\u4ef6\u540d\u79f0', max_length=100, validators=[spider.models.validate_name], verbose_name='\u914d\u7f6e\u540d\u79f0')),
                ('bot_ip', models.GenericIPAddressField(choices=[('182.92.75.82', '182'), ('43.243.136.230', '230')], default='0.0.0.0', verbose_name='\u76ee\u6807\u5730\u5740')),
                ('bot_port', models.IntegerField(choices=[(36800, '36800'), (36900, '36900')], default=0, verbose_name='\u76ee\u6807\u7aef\u53e3')),
                ('project_name', models.CharField(choices=[('example', '\u9879\u76ee1'), ('project2', '\u9879\u76ee2')], default='', max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('spider_name', models.CharField(choices=[('example', '\u722c\u866b1'), ('spider2', '\u722c\u866b2')], default='', max_length=100, verbose_name='\u722c\u866b\u540d\u79f0')),
                ('task_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4efb\u52a1\u65f6\u95f4')),
                ('job_id', models.CharField(default=0, editable=False, max_length=200, verbose_name='\u5de5\u4f5c\u5e8f\u53f7')),
                ('task_run', models.IntegerField(default=0, editable=False, verbose_name='\u4efb\u52a1\u53d1\u9001')),
            ],
            options={
                'db_table': 'spider_tasks',
                'verbose_name': '\u4efb\u52a1\u7ba1\u7406',
                'verbose_name_plural': '\u4efb\u52a1\u7ba1\u7406',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together=set([('protocol', 'ip', 'port')]),
        ),
    ]
